apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-helloworld-prod 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml 
    path: github_repo_suse/helm/python-helloworld
    repoURL: https://github.com/criticalhitx/SUSE_LAB 
    targetRevision: HEAD
